#' Hominin Part Abundance Dataset
#'
#' A dataset containing hominin part abundance data.
#'
#' @format A data frame with X rows and Y variables:
#' \describe{
#'   \item{column1}{Description of column1}
#'   \item{column2}{Description of column2}
#'   ...
#' }
#' @source Generated by \code{generate_newdata(5)}
"hpa"
